config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
              sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  resources :users, only: [:show, :edit, :update]
  resources :photo_posts, only: [:new, :show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  validates :username, presence: true, length: { maximum: 30 }, uniqueness: true
  has_many :photo_posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                              foreign_key: 'follower_id', dependent: :destroy
  has_many :following,
          through: 'active_relationships',
           source: 'followed'
  has_many :passive_relationship, class_name: 'Relationship',
                            foreign_key: 'followed_id', dependent: :destroy
  has_many :followers,
          through: 'passive_relationship',
           source: 'follower'
  mount_uploader :avatar, AvatarUploader
  validate :picture_size
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: 'likes', source: 'photo_post'

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def follow(other_user)
    following << other_user
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
  def feed
    following_ids = "SELECT followed_id FROM Relationships WHERE follower_id= :user_id"
    PhotoPost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
  
  private
  
    def picture_size
      if avatar.size > 4.megabytes
        errors.add(:avatar, "4メガバイトよりも小さい容量にしてください。")
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # You should also create an action method in this controller like this:
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  def failure
    redirect_to root_path
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :username, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(keys: [:password, :password_confirmation, :current_password])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
    
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      flash[:success] = "プロフィールが保存されました。"
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end
  
  private
  
    def update_user_params
      params.require(:user).permit(:email, :fullname, :username, :avatar,
                                    :website, :introduction, :sex)
    end
    

  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "フォローする", class: 'btn btn-outline-secondary' %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
        html: { method: :delete }) do |f| %>
  <%= f.submit 'フォロー中', class: 'btn btn-secondary' %>
<% end %>

app/views/users/_user.html.erb
<div class="d-flex mx-3 my-2 align-items-center">
  <div>
    <%= image_tag user.avatar, class: 'rounded-circle thumbnail' %>
  </div>
  <div class="mx-2">
    <%= link_to user.username, user, class: "text-wight-b font-weight-bold text-dark" %>
  </div>
</div>

app/views/users/_user_edit_form.html.erb
<% unless current_user == @user %>
  <div id="d-inline">
    <% if current_user.following?(@user) %>
     <%= render 'unfollow' %>
    <% else %>
     <%= render 'follow' %>
    <% end %>
  </div>
<% else %>
  <a href="<%=  edit_user_url current_user %>">
    <i class="fas fa-user-edit text-success"></i>
  </a>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<h1 class="text-center">Edit User</h1>
<div>
  <div class="row mb-3">
    <div class="col-md-7  col-sm-10 mx-sm-auto mx-4 mt-4">
      <div class="bg-white shadow-sm border mt-3">
        <ul class="nav nav-tabs m-2">
          <li class="nav-item"><a class="nav-link text-success  active font-weight-bold" href="<%= edit_user_registration_url %>">プロフィールを編集</a></li>
          <li class="nav-item"><a class="nav-link font-weight-light text-success" href="<%= edit_user_registration_url %>">パスワードを編集</a></li>
        </ul> 
        <div class="mx-3 my-4">
          <%= form_for @user, html: { method: :patch } do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            
            <div class="form-group">
              <%= f.label :fullname, "Full Name" %>
              <%= f.text_field :fullname, class: "form-control", placeholder: "Full name"  %>
            </div>
            
            <div class="form-group">
              <%= f.label :username, "User Name" %>
              <%= f.text_field :username, class: "form-control", placeholder: "User name"  %>
            </div>
            
            <div class="form-group d-flex align-items-center">
              <%= image_tag @user.avatar, class: "rounded-lg show-avatar" %>
              <%= f.file_field :avatar, accept:'image/jpeg, image/gif, image/png', class: "form-control-file" %>
            </div>
            
            <div class="form-group">
              <%= f.label :website, "Website" %>
              <%= f.text_field :website, class: "form-control", placeholder: "Website"  %>
            </div>
            
            <div class="m-2">
              <p class="text-center text-black-50">非公開情報</p>
            </div>
            
            <div class="form-group">
              <%= f.label :email, "Email" %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", type: "email", class: "form-control", placeholder: "Enter email" %>
            </div>
            
            <div class="form-group">
              <%= f.radio_button :sex, "男性"  %>
              <%= f.label :sex, "男性" %>
              <%= f.radio_button :sex, "女性"  %>
              <%= f.label :sex, "女性" %>
              <%= f.radio_button :sex, "その他"  %>
              <%= f.label :sex, "その他" %>
            </div>
            
            <div class="actions">
              <%= f.submit "Update", class: "btn btn-success my-2 btn-block" %>
            </div>
            
            <div class="my-3 d-flex justify-content-between flex-wrap">
              <%= link_to "アカウントを削除しますか", user_registration_url, method: :delete, class: "btn btn-outline-success d-block", data: { confirm: "本当に消去してもよろしいですか？" }  %>
              <%= link_to "ログアウト", destroy_user_session_url, method: :delete, class: "btn btn-outline-success d-block", data: { confirm: "本当にログアウトしますか？" }  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<div class="row mt-5">
  <div class="col-10 offset-1">
    <div class="row">
      <div class="col-lg-4 offset-lg-1 d-lg-inline-block m-auto">
        <%= image_tag @user.avatar, class: "rounded-circle d-block mx-auto my-3 show-avatar" %>
      </div>
      <div class="col-lg-6 d-lg-inline-block ml-2">
        <div class="mt-3 show-w text-center mx-lg-0 mx-auto">
          <div class="d-inline-block font-weight-bold show-user-name"><%= @user.username %></div>
          <div class="d-inline-block m-2"><%= render 'users/user_edit_form' %></div>
        </div>
        <div class="show-w mx-lg-0 mx-auto">
          <%= render 'shared/stats' %>
        </div>
      </div>
      <div class="w-75 m-auto">
        <div cass="font-weight-light">
          <%= @user.fullname %>    <span class="text-black-50"><%= @user.website %></span>
        </div>
        <div>
          <%= @user.introduction %>
        </div>
      </div>
      <div class="border-top mt-2 pt-2 d-flex flex-wrap show-photo-w mx-auto">
        <% @user.photo_posts.each do |p| %>
          <div class="pl-1">
            <a href="<%= photo_post_url(p) %>">
              <%= image_tag p.photo.thumb.url, class: "mb-1 show-thumb-photo" %>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>