config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
              sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  resources :users, only: [:show, :edit, :update]
  resources :photo_posts, only: [:new, :show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
end

app/models/photo_post.rb
class PhotoPost < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :description, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
  mount_uploader :photo, PhotoUploader
  validate :picture_size
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  def unlike(user)
    likes.find_by(user_id: user).destroy
  end
  
  def liked?(user)
    !likes.find_by(user_id: user.id).nil?
  end

  private
  
    def picture_size
      if photo.size > 4.megabytes
        errors.add(:photo, "4メガバイトよりも小さい容量にしてください。")
      end
    end
  
  
end

app/controllers/photo_posts_controller.rb
class PhotoPostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  
  def show
    @photo_post = PhotoPost.find(params[:id])
  end
  
  def new
    @photo_post = current_user.photo_posts.build
  end
  
  def create
    @photo_post = current_user.photo_posts.build(photo_post_params)
    if @photo_post.save
      flash[:success] = "投稿しました。"
      redirect_to @photo_post
    else
      render 'new'
    end
  end
  
  def destroy
    PhotoPost.find(params[:id]).destroy
    flash[:success] = "投稿を削除しました。"
    redirect_to root_url
  end
  
  private
    
    def photo_post_params
      params.require(:photo_post).permit(:photo, :description)
    end
    
    def correct_user
      photo = current_user.photo_posts.find_by(id: params[:id])
      redirect_to root_url if photo.nil?
    end
end

app/helpers/photo_posts_helper.rb
module PhotoPostsHelper
end

app/views/photo_posts/_photo_post.html.erb
<div class="border mb-5 shadow-sm">
  <a href="<%= user_path photo_post.user %>" class="text-dark">
    <div class="border d-flex pl-3 py-1 bg-white">
      <%= image_tag photo_post.user.avatar, class:"rounded-circle thumbnail mr-3" %>
      <div class="my-auto">
        <h5 class="mb-0"><%= photo_post.user.username %></h5>
      </div>
    </div>
  </a>
  <div>
    <div class="content">
      <a href="<%= photo_post_url photo_post %>">
        <%= image_tag photo_post.photo, class: "img-fluid border" %>
      </a>
    </div>
    <div class="bg-white border p-2">
      <div class="text-danger"><%= render 'shared/like_form', photo_post: photo_post %></div>
      <div>
        <span class="font-weight-bold"><%= photo_post.user.username %></span>
        <span><%= photo_post.description %></span>
      </div>
      <div class="p-2">
        <% photo_post.comments.each do |c| %>
          <div>
            <span class="text-info"><%= c.user.username %></span>
            <span class="font-weight-light pl-2"><%= c.content %></span>
          </div>
        <% end %>
      </div>
      <div class="w-100">
        <%= form_for(current_user.comments.build, url: comments_url) do |f| %>
          <%= hidden_field_tag :photo_post_id, photo_post.id, name: "comment[photo_post_id]" %>
          
          <div class="d-inline-block w-75"><%= f.text_field :content,class: 'comment-form border-0 w-100', placeholder: "コメントを追加…", required: "required"  %></div>
          <div class="d-inline-block"><%= f.submit '投稿する', class: "btn btn-outline-info btn-sm" %></div>
        <% end %>
      </div>
      <span class="timestamp text-black-50 font-weight-light">
        <%= time_ago_in_words(photo_post.created_at) %>前
      </span>
    </div>
  </div>
</div>

app/views/photo_posts/new.html.erb
<% provide(:title, 'upload') %>

<div>
  <%= form_for(@photo_post) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.file_field :photo, accept:'image/jpeg, image/gif, image/png' %>
    
    <%= f.text_area :description, class: 'form-control' %>
  
    <%= f.submit 'シェアする', class: "btn btn-primary" %>
  <% end %>
</div>

<script type="text/javascript">
  $('#photo_post_photo').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 4) {
      alert('最大容量は４メガバイドです。小さい容量のファイルを選んでください。');
    }
  });
</script>

app/views/photo_posts/show.html.erb
<% provide(:title, @photo_post.user.username) %>

<div class="row">
  <div class="col-8 offset-2 mx-auto my-3">
    <div class="photo-show border bg-white mx-auto">
      <div>
        <%= image_tag @photo_post.photo.url, class: "img-fluid" %>
      </div>
      <div>
        <div class="d-flex align-items-center mt-2 ml-3">
          <a href="<%= user_url(@photo_post.user) %>">
            <%= image_tag(@photo_post.user.avatar.url, class: "rounded-circle d-block ml-2 my-3 thumbnail") %>
          </a>
          <span class="ml-1 font-weight-bold">
            <%= render 'shared/like_form', photo_post: @photo_post %>
            <%= link_to @photo_post.user.username, @photo_post.user, class: " text-dark" %>
          </span>
          <a href="<%= photo_post_url(@photo_post) %>" rel="nofollow" data-method="delete" data-confirm="本当に消去してもよろしいですか？" class="ml-auto mr-3">
            <i class="far fa-trash-alt text-success fa-lg"></i>
          </a>
        </div>
        <div class="mx-3 mb-2">
          
          <%= @photo_post.description if @photo_post.description %>
          <div class="p-2">
            <% @photo_post.comments.each do |c| %>
              <div class="d-flex align-items-center">
                <span class="text-info"><%= c.user.username %></span>
                <span class="font-weight-light pl-2"><%= c.content %></span>
                <a href="<%= comment_path(c) %>"data-method="delete" data-confirm="本当に消去してもよろしいですか？" class="ml-auto mr-3">
                  <i class="fas fa-eraser text-dark fa-sm"></i>
                </a>
              </div>
            <% end %>
          </div>
          <div class="w-100">
            <%= form_for(current_user.comments.build, url: comments_url) do |f| %>
              <%= hidden_field_tag :photo_post_id, @photo_post.id, name: "comment[photo_post_id]" %>
              
              <div class="d-inline-block w-75"><%= f.text_field :content,class: 'comment-form border-0 w-100', placeholder: "コメントを追加…", required: "required"  %></div>
              <div class="d-inline-block"><%= f.submit '投稿する', class: "btn btn-outline-info btn-sm" %></div>
            <% end %>
          </div>
          <p class="text-black-50 font-weight-light"><%= time_ago_in_words(@photo_post.created_at) %>前</p>
        </div>
      </div>
    </div>
  </div>
</div>