config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
              sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  resources :users, only: [:show, :edit, :update]
  resources :photo_posts, only: [:new, :show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="border-top pt-4 px-3">
    <div class="float-left ">
      <small>
        © 2019 INSTAGRAM clone
      </small>
    </div>
    <% if user_signed_in? %>
      <div class="w-100">
        <div class="m-auto w-25 text-center">
          <a href="<%= new_photo_post_url %>" class="">
            <i class="far fa-plus-square fa-3x align-bottom text-success"></i>
          </a>
        </div>
      </div>
    <% end %>

  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="mb-4 py-3">
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-white navbar-light fixed-top">
        <div class="ml-md-5">
          <a href="<%= root_path %>" class="hanvbar-brand logo">
            <i class="fab fa-instagram fa-3x align-bottom"></i>
            <span class="logo-text pl-2">Instagram</span>
          </a>
        </div>
          
        <button class="navbar-toggler mr-1" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
          <ul class="navbar-nav mx-auto">
          </ul>
          
          <ul class="navbar-nav mr-5">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "My page", current_user, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8d223ae244.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <% message_type = "info" if message_type == "notice" %>
      <% message_type = "danger" if message_type == "alert" %>
        <%= content_tag(:p, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>